# Review
# Run build/test to ensure pull request will not break anything.
name: Review

on:
    - pull_request

jobs:
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: npm ci

            - name: Run a production build
              run: npm run build

            - name: Run tests
              run: npm run test